baseURL = "https://losthopes.github.io"
languageCode = "en-us"
title = "LostHope's blog"
theme = "blog-gruvbox-dark"

[markup.goldmark.parser.attribute]
block = true

[markup.tableOfContents]
endLevel = 3
startLevel = 1
ordered = false