name = 'Blog-gruvbox-dark'
license = 'MIT'
licenselink = 'https://github.com/LostHopes/losthopes.github.io/blob/main/themes/blog-gruvbox-dark/LICENSE'
description = 'Theme description'

# The home page of the theme, where the source can be found
homepage = 'https://github.com/LostHopes/losthopes.github.io/tree/main/themes/blog-gruvbox-dark'

# If you have a running demo of the theme
demosite = 'https://losthopes.github.io'

# Taxonomy terms
tags = ['blog', 'minimalistic', 'copywriting', 'life']
features = ['simple', 'insteresting', 'fast']

# If the theme has a single author
[author]
  name = 'LostHopes'
  homepage = 'https://losthopes.github.io'

# If porting an existing theme
[original]
  author = 'LostHopes'
  homepage = 'https://losthopes.github.io'
  repo = 'https://github.com/LostHopes/losthopes.github.io'
